### ISSUE TITLE
Failed tests with es6-module-transpiler@0.3.4 or later

### ISSUE THREAD

**Issue by okuryu** [kpdecker/es6-module-packager#5]
I tried out bump `es6-module-transpiler` version from 0.3.3 to 0.3.4 or latest (0.4.0) to implement YUI transpiler (see [es6-module-transpiler's changelog](https://github.com/square/es6-module-transpiler/blob/master/CHANGELOG.md#v034-tuesday-november-19-2013)), but it seems to fails to `es6-module-packager` tests.

So I'm not sure how to fix this problem.

**Comment by kpdecker** [comment]
Closing as this was going to be too much work and babel+webpack provide a solution that have larger ecosystems built around them.
